name: Wii Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitppc

    steps:
      - uses: actions/checkout@v4

      - name: Install Wii SDK
        run: |
          dkp-pacman -Sy --noconfirm
          dkp-pacman -S --needed --noconfirm wii-dev

      - name: Build
        run: |
          make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: wii-build
          path: |
            **/*.dol
            **/*.elf
