name: Wii Build (Stable Docker)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitppc:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Wii homebrew
        run: |
          make

      - name: Upload .dol
        uses: actions/upload-artifact@v4
        with:
          name: wii-build
          path: "*.dol"    
